### ISSUE TITLE
Missing index.js file.

### ISSUE THREAD

**Issue by D3nQ** [thatisuday/ng-image-gallery#23]
Your **package.json** states that the main file is **index.js**. But the file is nowhere to be found.

**Comment by thatisuday** [comment]
That's because its for front end. Index.js is not useful here as it doesn't
export anything. You can make one anyhow. Give  me a PR

**Comment by sebastiendan** [comment]
Why not using your main js file instead of index.js in your package.json? That way we could `require` your module by using its name only, even if you don't export anything (e.g. with webpack loaders).

**Comment by thatisuday** [comment]
Give me a PR
