### ISSUE TITLE
Extract modal DOM element and move it to higher level

### ISSUE THREAD

**Issue by sebastiendan** [thatisuday/ng-image-gallery#24]
`ng-image-gallery-modal` DOM element is inside `ng-image-gallery`. A modal should instead be placed at the highest possible DOM level in order to fit the whole screen and be centred. 

Right now, modal DOM element is limited to any hypothetical positioned parent. Maybe this is useful sometimes but I would say not in many cases.

Adding an option to change this would be great!

**Comment by thatisuday** [comment]
This parent element provide necessary binding to toggles many things. If I
take that away, I all need to do it use jQuery and JavaScript to do DOM
manipulation which not only increase the size of this plugin but also make
it more difficult to maintain.

**Comment by thatisuday** [comment]
There will be many watch and apply statement and I don't like it.

**Comment by sebastiendan** [comment]
You can use events instead of $watch which I don't like either. But I understand this would be a big change in your code...

**Comment by thatisuday** [comment]
Unfortunately yes.
