### ISSUE TITLE
Thumbs aren't working in IE

### ISSUE THREAD

**Issue by TheLegion** [thatisuday/ng-image-gallery#25]
Thumbs aren't displaying in IE because of using angular expressions in thumb's attribute 'style'. It should be replaced by 'ng-style'.

**Comment by thatisuday** [comment]
Oh. On it.

**Comment by TheLegion** [comment]
You can make it working by replace
`style="background-image:url({{image.thumbUrl || image.url}});"`
with
`ng-style="{ \'background-image\': \'url(\' + (image.thumbUrl || image.url) + \')\' }"`
Works nice in chrome, ff and ie.
By the way, thanks for such nice component :)
