### ISSUE TITLE
$scope.methods are not changed

### ISSUE THREAD

**Issue by vinchi777** [thatisuday/ng-image-gallery#30]
Im using ng-image-gallery inside a directive.

```
//in my directive
$scope.methods = {}

//how i declare
%ng-image-gallery{:'images' => 'images', :'methods' => 'methods'}

//when called from ng-click
$scope.methods.open is not a function
```

**Comment by thatisuday** [comment]
@vinchi777 put it inside $timeout block.

**Comment by thatisuday** [comment]
Let me know if it worked for ya

**Comment by vinchi777** [comment]
hmm.. still not working. I already wrapped in timeout block

**Comment by thatisuday** [comment]
If you are using `$scope.open_gallery` function, then you don't need to use timeout. What you need to understand is that your directive is post linked, that means when you write `<ng-image-gallery` inside your directive template, all models available to it is not coming from the parent controller or scope. 

Hence your need to pre link your directive, which means link all models to the controller first and then link all child directives. Hence, in this case, as your directive is prelinked, $scope.methods will be available to `<ng-image-gallery`. 


Please share your directive code or you can do like this
```
return {
  link : function preLink(){

 }
}
```

follow this https://www.undefinednull.com/2014/07/07/practical-guide-to-prelink-postlink-and-controller-methods-of-angular-directives/

**Comment by thatisuday** [comment]
Also, follow this http://stackoverflow.com/a/22105966/2790983

**Comment by thatisuday** [comment]
If you are making a component, follow this https://github.com/thatisuday/ng-dropzone/wiki/Working-with-angular-1.5-Component

**Comment by vinchi777** [comment]
pre linking works! thanks
