### ISSUE TITLE
Can display the description in the slideshow?

### ISSUE THREAD

**Issue by chanchilun** [thatisuday/ng-image-gallery#32]
The description only displayed as image alt currently, how about display the description of the image in the slideshow?

**Comment by thatisuday** [comment]
There is no such functionality yet. May be I can do it in next release. Can you give me some examples (share links)?

**Comment by chanchilun** [comment]
![capture](https://cloud.githubusercontent.com/assets/10358280/21445828/34cd7916-c8f9-11e6-9962-97232e5185f6.JPG)

Thank for your reply and the example like that:
https://sachinchoolur.github.io/lightGallery/#lg=1&slide=1

**Comment by thatisuday** [comment]
fixed in v2.1.0
