### ISSUE TITLE
removeClassFromDocumentBody is never called

### ISSUE THREAD

**Issue by kartoDeveloper** [thatisuday/ng-image-gallery#38]
The function removeClassFromDocumentBody is never called. 

The reason is a typo in directive.js on line 397. 

It should be:
$rootScope.$on('$routeChangeSuccess', removeClassFromDocumentBody);

**Comment by thatisuday** [comment]
@kartoDeveloper I couldn't replicate the problem. Can you explain how/where you are getting the error?

**Comment by kartoDeveloper** [comment]
If you look in your code on line 397, the name of the event has an additional blank at the end. Therefore the "removeClassFromDocumentBody" function is not called. The effect is not an error, but the class "body-overflow-hidden" is not removed from the document body and the result is that you will not be able to scroll in the browser anymore. Only a reload of the page removes this problem.

**Comment by thatisuday** [comment]
fixed in version 2.0.9
