### ISSUE TITLE
Thumbnails do not scroll 

### ISSUE THREAD

**Issue by anantheswarg881** [thatisuday/ng-image-gallery#39]
I have increased the size of thumbnails. But there is no scroll functionality on the thumbnails. Would be a good addition to have. 

Thanks!

**Comment by thatisuday** [comment]
@anantheswarg881 Can you share me screenshot?

**Comment by anantheswarg881** [comment]
![galleryerror](https://cloud.githubusercontent.com/assets/22448243/22461002/8724bae2-e7cd-11e6-8836-b4c55bfda62d.png)
Here is the screenshot. Please fix this. I love this gallery very much. I have tried other galleries. But they do not work well with data changes like adding images. Thanks!

**Comment by thatisuday** [comment]
fixed in v2.1.0
