### ISSUE TITLE
Icons not visible in Chrome when importing via Webpack

### ISSUE THREAD

**Issue by muenzel** [thatisuday/ng-image-gallery#44]
I have the strange issue that when I load ng-image-gallery via webpack (js und css) then in Chrome the icons (previous, next and the closing symbol) are not visible whereas in Safari they are visible.

When I change the url of the background-image in the developer tools to the absolute path (i.e. http://localhost:3000/xyz.svg) the image appears.

**Comment by thatisuday** [comment]
I am not sure if this plugin will work with webpack. But I will look into this issue.

**Comment by muenzel** [comment]
Actually everything is fine. I put it into production and the icons are all there, but it doesn't work in my development environment. I don't think it is an issue with ng-image-gallery at all.
