### ISSUE TITLE
Gallery has full height inside scrollable container, making it impossible to use

### ISSUE THREAD

**Issue by neslinesli93** [thatisuday/ng-image-gallery#45]
Hi, first of all thanks for the library - it's a breeze to use and it's very lightweight.

I'm trying to put a gallery inside a scrollable container, and I expected to have it centered inside the page, no matter the scroll position.
However, the result is that the gallery goes full height, which makes it ugly (because the pictures are not centered vertically) and impossible to use (because the bubbles and the top menu are not visible).
I tried to change divs position to `fixed` instead of `absolute`, but it ain't fix the problem.

Thanks again

**Comment by thatisuday** [comment]
@neslinesli93 Yes. It necessary to have position absolute else it won't work. But can you share me screenshot of the problem?

**Comment by neslinesli93** [comment]
Sorry, I had put the gallery inside a flex container and it was messing everything up.
Closing this
