### ISSUE TITLE
[BUG] When you click on an image through the bubbles, when you go to the next image (by using the mouse or the arrow keys) it selects the wrong one

### ISSUE THREAD

**Issue by neslinesli93** [thatisuday/ng-image-gallery#47]
It seems like clicking on a bubble doesn't change the internal order for displaying the images

**Comment by thatisuday** [comment]
@neslinesli93 I will look into it.

**Comment by neslinesli93** [comment]
Feel free to look in my fork, I've added a bunch of commits that may result useful to you and all the other users.
It's a very tiny and well done library, so I didn't feel like it was ok to make a PR.
However, you may like some of the problems that I've solved in my fork.

Thanks again for your hard work

**Comment by thatisuday** [comment]
@neslinesli93 Loved your hardwork in this. I would love a pull request.  Since you have done lot of work, see if you can come up with a solution for https://github.com/thatisuday/ng-image-gallery/issues/39

**Comment by thatisuday** [comment]
fixed in v2.1.0
