### ISSUE TITLE
thumbnail taking so much time while loading in browser

### ISSUE THREAD

**Issue by Webrusterkk** [thatisuday/ng-image-gallery#48]
Hello ,

Thanks for this wonderfull plugin, is there a way to lazy load the thumbnails , i am loading around 50 thumbnails and this causing the blocking of UI until all the thumbnails are loaded

**Comment by thatisuday** [comment]
@Webrusterkk Yeah, that's a good idea to lazy load thumbnails as well. But for now, use `thumbUrl` in your image object. Read documentation.

**Comment by Webrusterkk** [comment]
I modified your Code a bit by creating additional Directive to show loading while binding  here is the snippet  
Newly created Directive added in the **ng-image-gallery.js**
`.directive("showOnceBackgroundLoaded", [function () {
            return {
                restrict: "A",
                scope: false,
                link: function (scope, element, attributes) {
                    element.addClass("my-loader");
                    var image = new Image();
                    image.onload = function () {
                        // the image must have been cached by the browser, so it should load quickly
                        scope.$apply(function () {
                            element.css({ backgroundImage: 'url("' + attributes.showOnceBackgroundLoaded + '")' });
                            element.removeClass("my-loader");
                        });
                    };
                    image.src = attributes.showOnceBackgroundLoaded;
                }
            };
        }])`

part of the ng-imagegallery which i modified:

`
							// Thumbnails container
							//  Hide for inline gallery
//show-once-background-loaded is the directive that i have created above and using it here
							'<div ng-if="thumbnails && !inline" class="ng-image-gallery-thumbnails">' +
								'<div class="thumb" ng-repeat="image in images track by $index" ng-click="methods.open($index);" show-once-background-loaded="{{image.thumbUrl || image.url}}"  ng-attr-title="{{image.title || undefined}}"></div>' +
							'</div>' +

							// Modal container`


**my-loader** css

`.my-loader {
  background: transparent url('../images/loading_spinner.gif') center no-repeat;
}`

**Comment by StanleySathler** [comment]
@Webrusterkk wouldn't be a pull request better than posting it here? lol

Anyway, didn't test your feature, but looks fine. +1

**Comment by Webrusterkk** [comment]
@StanleySathler  lol, yeah , but just want to make sure this work .. will send a Pull request . I have tested it .. looks fine but would be better if get feedback response from the community ..

**Comment by thatisuday** [comment]
@Webrusterkk Let me deal with it just now... Will update you. I don't like the spinner part so have to come up with some background color. Will update you. Give me couple of hours.

**Comment by Webrusterkk** [comment]
In that loader class if u can give background colour then ur expectations will be met anyways take ur time , just want to share my implementation tat is the reason I haven't sent pull request . OnceAgain tanks for wonderful plugin .

**Comment by thatisuday** [comment]
fixed in v2.1.0
