### ISSUE TITLE
Possible to play Video files?

### ISSUE THREAD

**Issue by Hadryan** [thatisuday/ng-image-gallery#49]
Is it possible to make this script work with `video.js` to play video files in the modal window?

**Comment by thatisuday** [comment]
@Hadryan Unfortunately no. This plugin is meant to only serve image files. There are many things going on to generate thumbnails and lazy load images. Adding video will add more dependencies and we want to keep this plugin as lite as possible. I think you are looking for modal window with video to play in. Please have a look at my new project https://github.com/thatisuday/ng-full-modal, may be this can be helpful to you.
