### ISSUE TITLE
Functionality for callback if Image was not found on URL

### ISSUE THREAD

**Issue by fahimmahmoodmir** [thatisuday/ng-image-gallery#50]
There are some urls in images list which might return 404 error. if  "next" or "previous" anchors are click and that url returns  404 then script kept on showing progress indicator. is there any option or placeholder things or even a callback in this scenario of 404 error. Following are the images of this behavior:

![image](https://cloud.githubusercontent.com/assets/2732245/24460406/8246d372-149e-11e7-8894-bab7cf27c616.png)

and when i click on next or previous it kept on showing progress indicator:

![image](https://cloud.githubusercontent.com/assets/2732245/24460461/a1067286-149e-11e7-82c9-827bd8a3009a.png)

**Comment by thatisuday** [comment]
@fahimmahmoodmir Ooops. Missed that. Will fix it..
