### ISSUE TITLE
Duplicates in a repeater are not allowed.

### ISSUE THREAD

**Issue by mjknight50** [thatisuday/ng-image-gallery#56]
I have some images I am pulling from AWS that look like this:
[{"listingId":19,"photoName":"2135 Danby Road1.jpg","photoId":97,"isDefault":1,"photoUrl":"https://s3.amazonaws.com/cu-ssit-prod-offcampushousing/19%2F2135+Danby+Road.jpg"},
{"listingId":19,"photoName":"2135 Danby Road.jpg","photoId":96,"isDefault":0,"photoUrl":"https://s3.amazonaws.com/cu-ssit-prod-offcampushousing/19%2F2135+Danby+Road.jpg"}]

As you may be able to see, the photoId is different, as well as the photoName, however, the photoUrl is the same.

I take that JSON, and modify it like this to meet the JSON structure that you require:

                vm.photos  = [];
                for (var i = 0; i < photos.data.length; i++) {
                    vm.photos.push({ 'id': photos.data[i].photoId, 'url': photos.data[i].photoUrl });
                }

This results in
 Error: [ngRepeat:dupes] Duplicates in a repeater are not allowed. Use 'track by' expression to specify unique keys. Repeater: image in images track by image.url, Duplicate key: https://s3.amazonaws.com/cu-ssit-prod-offcampushousing/19%2F2135+Danby+Road.jpg, Duplicate value: {"id":96,"url":"https://s3.amazonaws.com/cu-ssit-prod-offcampushousing/19%2F2135+Danby+Road.jpg"}

I was under the impression that the **id** was what needed to be unique, which as you can see it is.

**Comment by thatisuday** [comment]
id needs to be unique. is `photos.data[i].photoId` unique. Else there might be a bug in the code...

**Comment by mjknight50** [comment]
Yes, it is unique.   Here is the JSON:
[{**"id":97,**"url":"https://s3.amazonaws.com/cu-ssit-prod-offcampushousing/19%2F2135+Danby+Road.jpg"},{"**id":96,**"url":"https://s3.amazonaws.com/cu-ssit-prod-offcampushousing/19%2F2135+Danby+Road.jpg"}]

**Comment by thatisuday** [comment]
Yup, there is a bug. Thumbnails generated are tracked by url. If you are not using thumbnails, just disable it. I will upload bug fix soon.

**Comment by thatisuday** [comment]
upgrade to v2.1.2 , that will do it

**Comment by mjknight50** [comment]
Yes, that did it.  Thank you!
