### ISSUE TITLE
Versions problem in https://mvnrepository.com

### ISSUE THREAD

**Issue by sintjuri** [thatisuday/ng-image-gallery#58]
There is a version 
https://mvnrepository.com/artifact/org.webjars.bower/github-com-thatisuday-ng-image-gallery/v2.0.8
it requires
org.webjars.bower » hammerjs [2.0.8,3) 
but available is 
2.0.6
Without hammerjs it doesn't work, so hammerjs is mandatory, not optional.

**Comment by thatisuday** [comment]
It's optional. Don't include the hammer.js script. It's working fine from here.

**Comment by sintjuri** [comment]
May be it is optional, but it seems that in pom it is mandatory:
https://mvnrepository.com/artifact/org.webjars.bower/github-com-thatisuday-ng-image-gallery/v2.0.8
and if somebody will try to add gallery as webjar to project, project can't be compiled, because there is non satisfied dependency to hammerjs
