### ISSUE TITLE
angular-ui-router version changed

### ISSUE THREAD

**Issue by LousyJohnny** [thatisuday/ng-image-gallery#59]
I had angular-ui-router 0.4.2 installed in my app before bower installing the image-gallery, and the installation changed this version in 0.3.0 ...  which is not cool for me. 
Have I done something wrong, or is it intended ?

**Comment by thatisuday** [comment]
This can't happen as ng-image-gallery has no `angular-ui-router` dependency.

**Comment by LousyJohnny** [comment]
You are absolutely right, the change have been provoked elsewhere. 
My bad, & thanks for the gallery.
